---
- hosts: jump-host
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: false
  vars:
    ansible_ssh_pipelining: false
  roles:
      - { role: bootstrap-os, tags: bootstrap-os}

- hosts: jump-host
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: false
  vars:
    ansible_ssh_pipelining: true
  roles:
      - { role: jump-mssql}