---
- name: Client-admin | Docker | Update
  apt: 
    update_cache: yes

- name: Client-admin | Docker | Install Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - curl
    - ca-certificates
    - software-properties-common

- name: Client-admin | Docker | Update key and repo
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
 
- name: Client-admin | Docker | Update
  apt: 
    update_cache: yes
 
- name: Client-admin | Docker | Install Docker
  apt:
    name: docker-ce

- name: Client-admin | Docker | Install Docker-py
  pip:
    name: docker
