---
- file: 
    path: /conf
    state: directory
    mode: 0775

- name: Client-admin | External nginx | Create config
  template:
    src: "{{ role_path }}/templates/nginx.conf.j2"
    dest: /conf/nginx.conf
    
- name: Client-admin | External nginx | Run container
  docker_container:
    name: nginx-external
    image: nginx
    ports:
    - "9080:80"
    - "9443:443"
    volumes:
    - "/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
  environment:
    DOCKER_HOST: unix://var/run/docker.sock