---
- name: NFS | Preinstall | Update
  apt: 
    update_cache: yes

- name: NFS | Preinstall | Install Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - curl
    - ca-certificates
    - software-properties-common

- name: NFS | Preinstall | Update key and repo
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
 
- name: NFS | Preinstall | Update
  apt: 
    update_cache: yes
 
- name: NFS | Preinstall | Install Docker
  apt:
    name: docker-ce

- name: NFS | Preinstall | Install Docker-py
  pip:
    name: docker

- name: NFS | Preinstall | Enable nfsd
  modprobe:
    name: nfsd
    state: present
    
- lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 nfs-server"
    
- file: 
    path: /conf
    state: directory
    mode: 0775   

- file: 
    path: /data
    state: directory
    owner: nobody
    group: nogroup
    mode: 0775   

- file: 
    path: /data/nfs_data
    state: directory
    owner: nobody
    group: nogroup
    mode: 0775  

- file: 
    path: /data/nfs_log
    state: directory
    owner: nobody
    group: nogroup    
    mode: 0775  

- file: 
    path: /data/nfs_backup
    state: directory
    owner: nobody
    group: nogroup    
    mode: 0775  
    
- name: NFS | Install | Set exports
  copy:
    dest: "/conf/exports"
    content: |
      /data {{ cluster_sub_net }}(rw,no_subtree_check,fsid=0)
      /data/nfs_data {{ cluster_sub_net }}(rw,insecure,nohide,all_squash,anonuid=1001,anongid=1001,no_subtree_check)
      /data/nfs_log {{ cluster_sub_net }}(rw,insecure,nohide,all_squash,anonuid=1001,anongid=1001,no_subtree_check)
      /data/nfs_backup {{ cluster_sub_net }}(rw,insecure,nohide,all_squash,anonuid=1001,anongid=1001,no_subtree_check) 
      
- name: NFS | Install | Run container
  docker_container:
    name: nfs-server
    image: erichough/nfs-server
    privileged: yes
    ports:
    - "2049:2049"
    volumes:
    - "/data:/data"
    - "/conf/exports:/etc/exports"
  environment:
    DOCKER_HOST: unix://var/run/docker.sock
    

